[MC-2359] Add normalized event and property names evaluation
CleverTap/clevertap-ios-sdk pull request #385
Opened 2024-11-14 08:41 UTC by nishant-clevertap

- Adds method `areEqualNormalizedName:` to check if two strings are normalized equal or not.
- Adds method `getNormalizedName:` to get normalized name after removing white spaces and converting it to lowercase with en_US locale.
- Added unit tests.

2024-11-14 10:33 UTC, nzagorchev commented
@nishant-clevertap Implementation looks good to me. Please add a comment on why this is done and why we use the English locale, see the android PR for details.

2024-11-14 11:15 UTC, nishant-clevertap commented
> @nishant-clevertap Implementation looks good to me. Please add a comment on why this is done and why we use the English locale, see the android PR for details.

Added method docs and comment.

2024-11-26 16:02 UTC, nzagorchev requested changes
We need to define the behavior if multiple properties equal the normalized property name, for example:
```
NSArray *whenTriggers = @[
    @{
        @"eventName": @"event1",
        @"eventProperties": @[
            @{
                @"propertyName": @"prop1",
                @"operator": @1,
                @"propertyValue": @"test"
            }
        ]
    }
];

match = [triggerMatcher matchEventWhenTriggers:whenTriggers eventName:@"event1" eventProperties:@{
    @"Prop  1": @"test1",
    @"Prop1": @"test",
    @"prop1": @"test2"
}];
```


We also need a test for the items keys normalization.

2024-11-28 09:36 UTC, vasct approved these changes

2024-11-28 11:07 UTC, merged