[MC-2363] Add parsing of url params on open-url action
CleverTap/clevertap-ios-sdk pull request #386
Opened 2024-11-15 16:57 UTC by nishant-clevertap

- Added parsing of urls on open-url action.
- This will track the parameters in url for in-app in Notification Clicked event.
- This will also parse `__dl__` if `wzrk_c2a` is present in query parameters or action URL.

2024-11-19 07:48 UTC, akashvercetti approved these changes

2024-11-19 09:12 UTC, vasct approved these changes

2024-11-20 20:04 UTC, nzagorchev requested changes
My understanding is that we want to apply the parsing of the URL params for all in-app templates. The current changes apply only to HTML templates that use the JS Interface triggerInAppAction.

The code added is a duplicate of the code in CTInAppHTMLViewController. Please, reuse the code, check if it is better to move it to handleNotificationAction and/or the utils.

2024-11-26 16:39 UTC, akashvercetti approved these changes

2024-11-26 18:21 UTC, merged